group=me.earthme.luminol
version=26.1.2-R0.1-SNAPSHOT
mcVersion=26.1.2
apiVersion=26.1.2
channel=ALPHA
clipVersion=3.0.15-20260413.051550-1
weightVersion=2.0.11
# 0 for skip release, 1 for pre-release, 2 for release
release=1

foliaRef=7458247e9b0fb382a789f572b100bbb3c9ca08b2

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
