group=me.earthme.luminol
version=26.1.2-R0.1-SNAPSHOT
mcVersion=26.1.2
apiVersion=26.1.2
channel=ALPHA

# 0 for skip release, 1 for pre-release, 2 for release
release=1

foliaRef=3de6e5b1a9b8a6f30248849991f856b10ed35183

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
