group=me.earthme.luminol
version=26.1.2-R0.1-SNAPSHOT
mcVersion=26.1.2
apiVersion=26.1.2
channel=BETA
clipVersion=3.0.16
weightVersion=2.0.12
# 0 for skip release, 1 for pre-release, 2 for release
release=1

foliaRef=2b6ba226a7e3d5f91a96358397b885e426dc8604

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
